[package]
name = "icebucket-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"